#!/bin/bash

bspc monitor '^1' -d I II III IV V VI VII VIII IX
bspc monitor '^2' -d X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Wrapper-2.0 monitor='^1' follow=on state=floating border=off rectangle=500x600+0+0
